import { Lab, PhDetectorData } from "@/types/lab";

const labdata: Lab[] = [

    {
        id: 1,
        name: "Acrylic Glass PCR Workstation",
        price: "Price: 55000 INR",
        size: "",
        supply: "5000000 Per Month",
        delivery: "1 Days",
        color: "Transparent",
        dimension: "",
        usage: "Lab Industry",
        warranty: "",
        type: "PCR Workstation",
        material: "Acrylic Glass",
        voltage: "Voltage: 220-240 Volt (v)",
        href: "",
        image: "/images/brands/Gel-Documentation-Machine.jpg"

    },
    {
        id: 2,
        name: "Digital Portable Cyberscan",
        supply: "5000000 Per Month",
        price: "Price: 35000 INR",
        delivery: "1 Days",
        color: "Blue-White-Grey",
        dimension: "",
        size: "",
        usage: "Lab Industry",
        warranty: "",
        type: "Digital Portable Cyberscan",
        material: "Plastic",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 3,
        name: "Galvanized Iron Redox Electrode",
        supply: "5000000 Per Month",
        price: "Price: 275000 INR",
        delivery: "1 Days",
        color: "Blue-White",
        dimension: "", size: "",
        usage: "Lab Industry",
        warranty: "",
        type: "Gel Documentation Machine",
        material: "Plastic",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 4,
        name: "Gel Documentation Machine",
        supply: "5000000 Per Month",
        price: "Price: 35000 INR",
        delivery: "1 Days",
        color: "Blue-White-Grey",
        dimension: "", size: "",
        usage: "Lab Industry",
        warranty: "",
        type: "Digital Portable Cyberscan",
        material: "Plastic",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 5,
        name: "Laboratory Top Loading Balance",
        supply: "Price: 60000 INR",
        price: "Price: 275000 INR",
        delivery: "1 Days",
        color: "White",
        dimension: "", size: "",
        usage: "Lab Industry",
        warranty: "",
        type: "Laboratory Top Loading Balance",
        material: "Plastic",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    }, {
        id: 6,
        name: "Oil Test Lab Centrifuge",
        supply: "5000000 Per Month",
        price: "Price: 19000 INR",
        delivery: "1 Days",
        color: "Blue",
        dimension: "", size: "",
        usage: "Lab Industry",
        warranty: "",
        type: "Oil Test Lab Centrifuge",
        material: "Mild Steel",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 7,
        name: "Semi Automatic Paper Electrophoresis System",
        supply: "5000000 Per Month",
        price: "Price: 12000 INR",
        delivery: "1 Days",
        color: "Blue",
        dimension: "", size: "",
        usage: "Lab Industry",
        warranty: "",
        type: "Paper Electrophoresis System",
        material: "Plastic",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 8,
        name: "Stainless Steel Electromagnetic Stirrer",
        supply: "5000000 Per Month",
        price: "Price: 14000 INR",
        delivery: "1 Days",
        color: "Blue-White",
        usage: "Lab Industry",
        dimension: "", size: "",
        warranty: "Warranty: 1 years",
        type: "Electromagnetic Stirrer",
        material: "Stainless Steel",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 9,
        name: "Double Beam Spectrophotometer",
        supply: "5000000 Per Month",
        price: "Price: 280000 INR",
        delivery: "1 Days",
        color: "Grey",
        usage: "Lab Industry",
        warranty: "",
        dimension: "", size: "",
        type: "Double Beam Spectrophotometer",
        material: "Plastic",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 10,
        name: "Heavy Duty Lab Centrifuge",
        supply: "5000000 Per Month",
        price: "Price: 19000 INR",
        delivery: "1 Days",
        color: "Blue",
        usage: "Lab Industry",
        warranty: "",
        dimension: "", size: "",
        type: "Lab Centrifuge",
        material: "Stainless Steel",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 11,
        name: "High Quality Semi Micro Balance",
        supply: "5000000 Per Month",
        price: "Price: 60000 INR",
        delivery: "1 Days",
        dimension: "", size: "",
        color: "White",
        usage: "Lab Industry",
        warranty: "",
        type: "Semi Micro Balance",
        material: "Plastic-Glass",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 12,
        name: "Laboratory Submarine Electrophoresis System",
        supply: "5000000 Per Month",
        price: "Price: 12000 INR",
        delivery: "1 Days",
        color: "Blue",
        usage: "Lab Industry",
        warranty: "",
        dimension: "", size: "",
        type: "Laboratory Submarine Electrophoresis System",
        material: "Stainless Steel",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 13,
        name: "Multimag Magnetic Stirrer",
        supply: "5000000 Per Month",
        price: "Price: 14000 INR",
        delivery: "1 Days",
        color: "White",
        dimension: "", size: "",
        usage: "Lab Industry",
        warranty: "Warranty: 1 years",
        type: "Multimag Magnetic Stirrer",
        material: "Stainless Steel",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 14,
        name: "Stainless Steel Hotplate Magnetic Stirrer",
        supply: "5000000 Per Month",
        price: "Price: 36000 INR",
        delivery: "1 Days",
        color: "Blue-White",
        usage: "Lab Industry",
        dimension: "", size: "",
        warranty: "Warranty: 1 years",
        type: "Multimag Magnetic Stirrer",
        material: "Stainless Steel",
        voltage: "230 Volt (v)",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 15,
        name: "Blood Bank Centrifuge",
        supply: "5000000 Per Month",
        price: "Price: 19000 INR",
        delivery: "1 Days",
        dimension: "", size: "",
        color: "White-Black",
        usage: "Lab Industry",
        warranty: "Warranty: 1 years",
        type: "Blood Bank Centrifuge",
        material: "Plastic",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },

    {
        id: 16,
        name: "Digital Laboratory Balance",
        supply: "5000000 Per Month",
        price: "Price: 60000 INR",
        delivery: "1 Days",
        dimension: "", size: "",
        color: "White",
        usage: "Lab Industry",
        warranty: "",
        type: "Digital Laboratory Balance",
        material: "Plastic-Glass",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 17,
        name: "Mild Steel Hot Plate",
        supply: "5000000 Per Month",
        price: "Price: 5000 INR",
        delivery: "1 Days",
        dimension: "",
        size: "12 Inch",
        color: "Blue-White-Black",
        usage: "Lab Industry",
        warranty: "",
        type: "",
        material: "Mild Steel",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 18,
        name: "Semi Automatic Horizontal Electrophoresis System",
        supply: "5000000 Per Month",
        price: "Price: 12000 INR",
        delivery: "1 Days",
        color: "White",
        dimension: "", size: "",
        usage: "Lab Industry",
        warranty: "Warranty: 1 years",
        type: "Horizontal Electrophoresis System",
        material: "Plastic",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 19,
        name: "Chemical Basket Centrifuge",
        supply: "5000000 Per Month",
        price: "Price: 19000 INR",
        delivery: "1 Days",
        color: "Blue-White-Silver",
        dimension: "", size: "",
        usage: "Lab Industry",
        warranty: "",
        type: "Multimag Magnetic Stirrer",
        material: "Stainless Steel",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
    {
        id: 20,
        name: "Digital Flame Photometer",
        supply: "5000000 Per Month",
        price: "Price: 58000 INR",
        delivery: "1 Days",
        color: "Blue-White",
        dimension: "",
        size: "",
        usage: "Lab Industry",
        warranty: "",
        type: "Digital Flame Photometer",
        material: "",
        voltage: "",
        href: "",
        image: "/images/brands/Multimag-Magnetic-Stirrer.jpg"

    },
]


const phdetectorDatas: PhDetectorData[] =
    [
        {
            id: 1,
            price: "Price: 4000 INR",
            name: "PH Field Monitor",
            supply: "5000000 Per Month",
            delivery: "Ph Detector Delivery",
            color: "Blue",
            dimension: "Ph Detector Dimension",
            size: "Ph Detector Size",
            warranty: "Ph Detector Warranty",
            type: "Ph Detector Type",
            usage: "Ph Detector Usage",
            controlmode: "Digital",
            material: "Plastic",
            voltage: "Ph Detector Voltage",
            href: "",
            image: "/images/phdetector/PH-Field-Monitor.jpg",
        },
        {
            id: 2,
            price: "Price: 5000 INR",
            name: "PH Field Monitor",
            supply: "5000000 Per Month",
            delivery: "Ph Detector Delivery",
            color: "Blue",
            dimension: "Ph Detector Dimension",
            size: "Ph Detector Size",
            warranty: "Ph Detector Warranty",
            type: "Ph Detector Type",
            usage: "Ph Detector Usage",
            controlmode: "Digital",
            material: "Plastic",
            voltage: "Ph Detector Voltage",
            href: "",
            image: "/images/phdetector/PH-Field-Monitor.jpg",
        },
        {
            id: 3,
            price: "Price: 6000 INR",
            name: "PH Field Monitor",
            supply: "5000000 Per Month",
            delivery: "Ph Detector Delivery",
            color: "Blue",
            dimension: "Ph Detector Dimension",
            size: "Ph Detector Size",
            warranty: "Ph Detector Warranty",
            type: "Ph Detector Type",
            usage: "Ph Detector Usage",
            controlmode: "Digital",
            material: "Plastic",
            voltage: "Ph Detector Voltage",
            href: "",
            image: "/images/phdetector/PH-Field-Monitor.jpg",
        },
        {
            id: 4,
            price: "Price: 7000 INR",
            name: "PH Field Monitor",
            supply: "5000000 Per Month",
            delivery: "Ph Detector Delivery",
            color: "Blue",
            dimension: "Ph Detector Dimension",
            size: "Ph Detector Size",
            warranty: "Ph Detector Warranty",
            type: "Ph Detector Type",
            usage: "Ph Detector Usage",
            controlmode: "Digital",
            material: "Plastic",
            voltage: "Ph Detector Voltage",
            href: "",
            image: "/images/phdetector/PH-Field-Monitor.jpg",
        },
    ]







export { labdata, phdetectorDatas }


